name: Deploy to Production Server

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:prod-${{ github.event.pull_request.number }} .
          docker tag ghcr.io/${{ github.repository }}:prod-${{ github.event.pull_request.number }} ghcr.io/${{ github.repository }}:prod-latest

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:prod-${{ github.event.pull_request.number }}
          docker push ghcr.io/${{ github.repository }}:prod-latest    

      - name: Call cloud-infra Workflow to deploy
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GHCR_RO_TOKEN }}" \
            -d '{
                  "ref": "main",
                  "inputs": {
                    "content": "",
                    "name": "${{ github.event.repository.name }}.env.prod"
                  }
                }' \
            https://api.github.com/repos/alva-systems/cloud-infra/actions/workflows/main.yml/dispatches